Fix strict compilation due to r47519
Fixes the following compiler error:
src/scripting/lua.cpp:1565: error: suggest parentheses around ‘&&’ within ‘||’

I hope to have got the logic right here. Anonymissimus should confirm.

git-svn-id: http://svn.gna.org/svn/wesnoth/trunk@47520 75b3775d-3801-0410-9e12-e2e43121521d